config/routes.rb
TEST::Application.routes.draw do
  resources :letters	
  resources :users
  root to: "users#index" # root_path # users_path
end

app/models/letter.rb
class Letter < ActiveRecord::Base
  attr_accessible :description, :titel, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :age, :name, :surname
  has_many :letters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
	before_filter :find_letter, only: [:show, :destroy, :edit, :update]

	def index
		@letters = Letter.all
	end

	def new
		@letter = Letter.new
	end

	def create
		@letter = Letter.new(params[:letter])
		if @letter.save
			redirect_to letters_path
		else
			render :new
		end
	end

	def update
		if @letter.update_attributes(params[:letter])
			redirect_to letters_path
		else
			render :edit
		end
	end

	def destroy
		@letter.destroy
		redirect_to letters_path
	end
	
	private
		def find_letter
			@letter = Letter.find(params[:id])
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :find_user, only: [:show, :destroy, :edit, :update]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to users_path
		else
			render :new
		end
	end

	def update
		if @user.update_attributes(params[:user])
			redirect_to users_path
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		redirect_to users_path
	end
	
	def show
		@letters = Letter.where(user_id: params[:id])
	end

	private
		def find_user
			@user = User.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TEST</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "users", users_path %>
<%= link_to "letters", letters_path %>
<%= yield %>

</body>
</html>

app/views/letters/_form.html.erb
<%= simple_form_for @letter do |f| %>
	<%= f.input :titel, label: "Title" %>
	<%= f.input :user_id, collection: User.all %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>
<%= link_to "back", letters_path %>

app/views/letters/edit.html.erb
<h style="font-family: MS Georgia; color: green; font-size: 25px">Edit Letter</h>
<%= render partial: "form" %>

app/views/letters/index.html.erb
<%= link_to "new", new_letter_path %>

<center>
	<table border="1px">
		<thead>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th colspan="3">Action</th>
			</tr>
		</thead>
		<tbody>
			<% @letters.each do |u| %>
				<tr>
					<td><%= u.titel %></td>
					<td><%= u.description %></td>
					<td><%= link_to "show", u %></td>
					<td><%= link_to "edit", edit_letter_path(id: u.id) %></td>
					<td><%= link_to "delete", letter_path(id: u.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>		
		</tbody>
	</table>
</center>

app/views/letters/new.html.erb
<h style="color: forestgreen; font-family: Times New Roman; font-size: 25px">New Letter</h>
<%= render partial: "form" %>

app/views/letters/show.html.erb
<center>
	<div style="width: 800px">
		<table border="1px" width="400px">
			<tr>
				<td align="right" width="80px">Title:</td>
				<td><%= @letter.titel %></td>
			</tr>
			<tr>
				<td align="right">Description:</td>
				<td><%= @letter.description %></td>
			</tr>
			
		</table>
		<div style="float: right">
			<%= link_to "back", :back %><br>
			<%= link_to "delete", letter_path(@letter.id), method: :delete, data: { confirm: 'Are you sure?' } %><br>
			<%= link_to "edit", edit_letter_path(@letter.id) %>
		</div>
	</div>
</center>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
	<%= f.input :name %>
	<%= f.input :surname %>
	<%= f.input :age %>
	<%= f.button :submit %>
<% end %>
<%= link_to "back", root_path %>

app/views/users/edit.html.erb
<h style="font-family: MS Georgia; color: green; font-size: 25px">Edit object</h>
<%= render partial: "form" %>

app/views/users/index.html.erb
<%= link_to "new", new_user_path %>

<center>
	<table border="1px">
		<thead>
			<tr>
				<th>Name</th>
				<th>Surname</th>
				<th>Age</th>
				<th colspan="3">Action</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |u| %>
				<tr>
					<td><%= u.name %></td>
					<td><%= u.surname %></td>
					<td><%= u.age %></td>
					<td><%= link_to "show", u %></td>
					<td><%= link_to "edit", edit_user_path(id: u.id) %></td>
					<td><%= link_to "delete", user_path(id: u.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>		
		</tbody>
	</table>
</center>

app/views/users/new.html.erb
<h style="color: forestgreen; font-family: Times New Roman; font-size: 25px">New object</h>
<%= render partial: "form" %>

app/views/users/show.html.erb
<center>
	<div style="width: 800px">
		<table border="1px" width="400px">
			<tr>
				<td align="right" width="80px">Name:</td>
				<td><%= @user.name %></td>
			</tr>
			<tr>
				<td align="right">Surname:</td>
				<td><%= @user.surname %></td>
			</tr>
			<tr>
				<td align="right">Age:</td>
				<td><%= @user.age %></td>
			</tr>
		</table>
		<div style="float: right">
			<%= link_to "back", :back %><br>
			<%= link_to "delete", user_path(@user.id), method: :delete, data: { confirm: 'Are you sure?' } %><br>
			<%= link_to "edit", edit_user_path(@user.id) %>
		</div>
	</div>
</center>

<br>
<center>
	<table border="1px">
		<thead>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th colspan="3">Action</th>
			</tr>
		</thead>
		<tbody>
			<% @letters.each do |u| %>
				<tr>
					<td><%= u.titel %></td>
					<td><%= u.description %></td>
					<td><%= link_to "show", u %></td>
					<td><%= link_to "edit", edit_letter_path(id: u.id) %></td>
					<td><%= link_to "delete", letter_path(id: u.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>		
		</tbody>
	</table>
</center>